name: install
on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  unixish:
    name: ${{ matrix.os }} ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
#           - runner: ubuntu-20.04
#             os: linux
          - runner: macos-10.15
            os: osx
    runs-on: ${{ matrix.runner }}
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies for Linux
        if: matrix.os == 'linux'
        run: |
          sudo apt-get install -y gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip build-essential
          sudo bash ./bin/install-latest-neovim
      - name: Installl dependencies for OSX
        if: matrix.os == 'osx'
        run: |
          brew update >/dev/null
          brew upgrade
          brew install neovim
      - name: Install StarVim
        run: |
          bash ./bin/installer
      - name: Test StarVim PackerCompile
        run: if nvim --headless +PackerCompile -c ':qall' 2>&1|grep -q 'Error'; then false; fi

      - name: Test StarVim Health
        run: if nvim --headless +checkhealth -c ':qall' 2>&1|grep -q 'Error'; then false; fi
